// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0XaZPLCdjf0WYKJ6YqLfFX8dUQHYpyPQ',
    appId: '1:689497472484:android:93e4e1d987073462805bf1',
    messagingSenderId: '689497472484',
    projectId: 'mungan-eco',
    storageBucket: 'mungan-eco.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMNJD-egBPW7ALNX4u_25CVDrGrX-GbV4',
    appId: '1:689497472484:ios:d48b8ba783d8796a805bf1',
    messagingSenderId: '689497472484',
    projectId: 'mungan-eco',
    storageBucket: 'mungan-eco.appspot.com',
    iosClientId: '689497472484-mv4idvitra0i9vbt7jpvmlthj70booln.apps.googleusercontent.com',
    iosBundleId: 'com.example.munganEco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMNJD-egBPW7ALNX4u_25CVDrGrX-GbV4',
    appId: '1:689497472484:ios:d48b8ba783d8796a805bf1',
    messagingSenderId: '689497472484',
    projectId: 'mungan-eco',
    storageBucket: 'mungan-eco.appspot.com',
    iosClientId: '689497472484-mv4idvitra0i9vbt7jpvmlthj70booln.apps.googleusercontent.com',
    iosBundleId: 'com.example.munganEco',
  );
}
